version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "gradle/"
    schedule:
      interval: "daily"
      time: "08:21"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    target-branch: "develop"
#  - package-ecosystem: "gradle"
#    directory: "gradle/"
#    schedule:
#      interval: "daily"
#      time: "07:58"
#      timezone: "Europe/Berlin"
#    allow:
#      - dependency-type: "direct"
#      - dependency-name: "org.jetbrains.kotlin"
#      - dependency-name: "androidx.compose.compiler"
#    labels:
#      - "dependencies, compose, kotlin"
#    commit-message:
#      prefix: "deps-compose-kotlin:"
#      include: "scope"
#    target-branch: "develop"