version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "gradle/"
    schedule:
      interval: "daily"
      time: "14:09"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps:"
      include: "scope"
  - package-ecosystem: "gradle"
    directory: "gradle/"
    schedule:
      interval: "daily"
      time: "14:09"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "direct"
      - dependency-name: "org.jetbrains.kotlin"
      - dependency-name: "androidx.compose.compiler"
    labels:
      - "dependencies, compose, kotlin"
    commit-message:
      prefix: "deps-compose-kotlin:"
      include: "scope"