version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:50"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    create-merge-commit: false
    group: "dependabot-updates"
  - package-ecosystem: "gradle"
    directory: "gradle/"
    schedule:
      interval: "daily"
      time: "00:50"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "direct"
      - dependency-name: "org.jetbrains.kotlin"
      - dependency-name: "androidx.compose.compiler"
    labels:
      - "dependencies"
    create-merge-commit: false
    group: "dependabot-updates-kotlin-compose"
