name: Android Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report-index.html
          path: app/build/reports/lint-results-debug.html