name: Unit Test

permissions:
  contents: read
  checks: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          require_tests: true
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Install JUnit report merger
        run: npm install -g junit-report-merger
      - name: run report merger
        run: jrm app/build/reports/tests/combined.xml "**/test-results/**/TEST-*.xml"

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v4
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: app/build/reports/tests/combined.xml # path to where the xml test results are stored
