name: Unit Test

permissions:
  contents: read
  checks: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run unit tests
        run: |
          ./gradlew testDebugUnitTest

      - name: Generate Test Report
        uses: test-summary/action@v4.0.0
        with:
          path: |
            '**/build/test-results/test/TEST-*.xml'
