name: Unit Test

permissions:
  checks: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run unit tests
        run: |
          ./gradlew clean test

      - name: Generate Test Report
        uses: mikepenz/action-junit-report@v2.1.0
        with:
          path: '**/build/test-results/**/*.xml'
          fail_on_empty: true
